service: aws-regression-lambda
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  memorySize: 1024
  timeout: 300
package:
  include:
    - app/**
    - libs/**
    - system/**
    - node_modules/**
    - handler.js
  exclude:
    - tests/**
    - server.js
functions:
  getLinearRegressionModel:
    handler: handler.getLinearRegressionModel
    events:
      - http:
          path: lambda/regression/linear/get-model/{_id}
          method: get
  createLinearRegressionModel:
    handler: handler.createLinearRegressionModel
    events:
      - http:
          path: lambda/regression/linear/create-model
          method: post
  trainLinearRegressionModel:
    handler: handler.trainLinearRegressionModel
    events:
      - http:
          path: lambda/regression/linear/train-model/{_id}
          method: post
  deleteLinearRegressionModel:
    handler: handler.deleteLinearRegressionModel
    events:
      - http:
          path: lambda/regression/linear/delete-model/{_id}
          method: delete